### ISSUE TITLE
Somewhat confusing error message on ArgumentError

### ISSUE THREAD

**Issue by nyaray** [whatyouhide/stream_data#105]
So, I've been learning how to use the StreamData-implementation of property-based tests and found myself confused at times. One of the issues is that `one_of` expects generators:

```
  1) property show error messages (Airweb.AirTimeTest)
     test/airtime_test.exs:120
     ** (ArgumentError) expected a generator, which can be a %StreamData{} struct, an atom, or a tuple with generators in it, but got: "baz"
     code: check all member <- one_of(["foo", "bar", "baz"]) do
     stacktrace:
       (stream_data) lib/stream_data.ex:228: anonymous fn/3 in StreamData.bind_filter/5
       (stream_data) lib/stream_data/lazy_tree.ex:34: StreamData.LazyTree.map/2
       (stream_data) lib/stream_data.ex:381: StreamData.bind_filter/5
       (stream_data) lib/stream_data.ex:348: anonymous fn/5 in StreamData.bind_filter/3
       (stream_data) lib/stream_data.ex:201: StreamData.bind_filter/5
       (stream_data) lib/stream_data.ex:348: anonymous fn/5 in StreamData.bind_filter/3
       (stream_data) lib/stream_data.ex:201: StreamData.check_all/7
       test/airtime_test.exs:121: (test)
```

I'd like something along the lines of the following to be the error description:

```
[...] expected a generator, which can be a %StreamData{} struct, an atom, or a tuple with generators in it, but got: "baz".
If you intended to use constants with `one_of`, you should remember to wrap them in `constant/1` calls.
Did you mean to use `member_of/1`, which accepts unwrapped terms?
```

- This helps users find member_of in situations where they want to use it and tells people what they could do to proceed.

**Comment by whatyouhide** [comment]
The problem with this is that instead of relying on *calling* a generator to find out if it's a generator or not, we will have to go through the list of generators in `one_of/1` and verify they are indeed generators. Doing this will also duplicate the logic of checking if something is a generator in two places, and it will be very special-cased to `one_of`. I think we can maybe improve the generic "expected a generator" message saying that if you want to use a term as a constant generator then you can use `constant/1`, but I am not convinced about special casing `one_of/1`. @josevalim thoughts?

**Comment by josevalim** [comment]
Yes, I agree we should try to improve the base message first. Then only if necessary we bring it up to the `one_of` generator too.
