### ISSUE TITLE
Integer Generator Values Bound by Run Size

### ISSUE THREAD

**Issue by Dzol** [whatyouhide/stream_data#109]
It seems that values generated by the `integer/1` generator are bound by `:max_runs`. E.g. if 100 then -100 =< integer/1 =< +100 (property test below). I expected a bigger set of values (and ones that are less predictable).

```Elixir
  property "integer/1 bound by run size" do

    x = 100; Application.put_env(:stream_data, :max_runs, x)

    check all i <- integer() do
      assert i >= -x
      assert i <= x
    end

    y = 3_210; Application.put_env(:stream_data, :max_runs, y)

    check all i <- integer() do
      assert i >= -y
      assert i <= y
    end

    check all l <- list_of(integer(), min_length: 1) do
      assert Enum.min(l) >= -y
      assert Enum.max(l) <= y
    end
  end
```

**Comment by Dzol** [comment]
The more I think about this the more I come to the conclusion that it's really about choosing `integer/0` bounds. I mean that what constitutes _good_ default `integer/0` bounds is a hard question. Perhaps the solution, when we need particular bounds or a wider bounds, is to just use `integer/1`.

**Comment by whatyouhide** [comment]
Also note so many generators build on top of `integer/0`. For example, `list_of/1` uses `integer/0` to determine the size of the list (so that we get shrinking towards an empty list for free): this means that if we generate large integers, we're bound to turn some generators into monsters :).

So given that you can easily and granularly customize what `integer/0` generates, that there's no clear best strategy on what to generate, and that so many generators rely on `integer/0`, I'm gonna go ahead and live things like they are now. Closing the issue, feel free to reopen or comment here if you have more to say.

Thanks for contributing! 💟
