### ISSUE TITLE
Nested `property` inside `describe` cannot access variables from outer context

### ISSUE THREAD

**Issue by Qqwy** [whatyouhide/stream_data#116]
When nesting `property`-blocks below a `describe`-block, these inner blocks cannot access variables in the outer context.

This can be a problem when e.g. we wrap the System Under Test (SUT) in an anonymous function that is to be used by the various `check`s contained in the `property` blocks.

The reason to set up your testing code like this, is that having a single property with multiple, potentially unrelated `check all` blocks that check for different properties of the system under test, is complicated and cannot be described properly because `check all`-blocks do not allow to add a humanly-readable description.

If we have a `describe`-block, it can contain a description of the system under test, and have multiple well-described `property`-blocks (each with potentially multiple `checks`, one for the success condition and one per known failure condition).

However, currently, accessing e.g. an anonymous function or other variable defined in the outer scope (the scope of the `describe`-block) from within a nested `property` / `check all` block does not work.

**Comment by whatyouhide** [comment]
Can you give a practical example please? If I am understanding correctly, this is not a StreamData limitation but an Elixir limitation.

**Comment by Qqwy** [comment]
I'll write a simple, self-contained example for this tomorrow morning.

I can already show the code in which I stumbled upon this:

[Planga.Chat.Events.ReducerTest](https://github.com/ResiliaDev/Planga/blob/teavent/test/chat/events/reducer_test.exs#L15).

In this property, I am actually testing three properties of the message content that is being sent in an event:

- empty strings are rejected
- too long strings are rejected
- strings with a non-empty small length are accepted.

Currently there is a `check` for each of them, within the same `property`, which means the test failure output can only be very inspecific.
However, rewriting this to have a `property` block (with a contained `check all`) for each of these cases makes it impossible to access variables as well as `@defines` from the outer scope, which would result in a lot of duplication.


It might very well be a limitation of the way `ExUnit` currently is designed, since a `property` === a `test` [as far as ExUnit is concerned](https://hexdocs.pm/ex_unit/ExUnit.Case.html#register_test/4), whereas a property actually runs a bunch of tests.

---

More tomorrow morning :-)

**Comment by Qqwy** [comment]
O.K., I made a small example repository that has no dependencies except for stream_data.

https://github.com/Qqwy/elixir-stream_data-property-example

The version of the test code that compiles [is here[(https://github.com/Qqwy/elixir-stream_data-property-example/blob/master/test/stream_data_example_test.exs), whereas in the `desired` branch I've rewritten it to the way I'd like to use it; [see here](https://github.com/Qqwy/elixir-stream_data-property-example/blob/desired/test/stream_data_example_test.exs).

The fictious System Under Test is `StreamDataExample.halve_even`, [in this file](https://github.com/Qqwy/elixir-stream_data-property-example/blob/desired/lib/stream_data_example.ex).

**Comment by whatyouhide** [comment]
Okay, I see what you mean now. First of all, that has nothing to do with StreamData. If you swap `property` with `test` and use just ExUnit, you won't be able to use functions outside of the scope of a `test` inside that `test`. This is actually a limitation of Elixir: whatever is outside of `test`/`property` and a bunch of other things (`def*` for example) is executed at compile-time. What is inside `test`/`property` is executed at runtime. An anonymous function carries a closure of its environment with it, so you can't define one at compile-time (outside `property`) and use it at runtime (inside `property`). If you want to bring over simple values as variables, the way to do that is `unquote`ing them inside the `property`.

The correct way of achieving what you're trying to achieve is to use plain old private functions. Put the common stuff in a private function and call it from the properties. If you have never used setup callbacks, those would be an even better idea: put the common stuff in `setup`/`setup_all` callbacks so that they're executed before each test. Have a look at the docs for [ExUnit callbacks](https://hexdocs.pm/ex_unit/ExUnit.Callbacks.html).

Closing this, but thanks a lot for the detailed report!

**Comment by Qqwy** [comment]
Thank you for your detailed response. Using named private functions is probably the correct solution for my use-case. Good catch! :+1:
