### ISSUE TITLE
Purpose of 'all' in `check all` and `gen all`?

### ISSUE THREAD

**Issue by Qqwy** [whatyouhide/stream_data#119]
Currently the `all` part that is used in `StreamData.check all` and `ExUnitProperties.gen all` is not well-documented. 

The current situation has two problems:
1. It is 'magical' because an extra word is added as embellishment to a function name. (So we have a  'function name' consisting of two words with a space in-between, rather than using an underscore). This moves the StreamData DSL further away from normal Elixir than it potentially needs to. 
2. Debugging. Take for example the following snippet:

```elixir
email_generator =
  ExUnit.Properties.gen all name <- StreamData.string(:alphanumeric),
  name != "",
  domain <- StreamData.member_of(domains) do
  name <> "@" <> domain
end
```
This will fail with the non-descriptive error message `** (CompileError) location:8: undefined function all/3`, rather than explaining my mistake (typing `ExUnit.Properties` instead of `ExUnitProperties`).

- Why is this 'fake keyword' used? Are there thoughts for future extension that would use other words instead of 'all'? Since we're pre-1.0, it might still be possible to make the breaking change to move away from it.
- Are there ways we can improve the documentation of `StreamData.check` and `ExUnitProperties.gen` so the usage of `all` is better explained?
- Are there ways we can make errors like above more clear, by for instance making `all` itself a function or macro that will print a better compiler error if it is used in an inappropriate context (and will not be called at all because the outer macro will 'eat' it if used in the appropriate context?)

**Comment by whatyouhide** [comment]
The `all` is there because arguments to the `check` and `gen` macros cannot be of variable amount. To rephrase that, you cannot have a macro in Elixir that takes an unspecified number of arguments. every clause (`x <- y`) is an argument. With the `all` trick, we're basically passing the AST of the call to `all(x <- y, w <- z, ...)` to the `check`/`gen` macros. Since the arity of a function call is not checked at macro expansion time, this works and lets us basically have variable-argument macros without having to change the language. Note that `with` and `for` (which use the `<-` clauses) are special forms in the language that are allowed to take a variable number of arguments.

Making `all` a function by itself won't help since if you incorrectly import/use `ExUnitProperties` then you won't have `all` either.

For now, this is as good as it gets. Hopefully this answers your questions, if not let me know. 💟
