### ISSUE TITLE
Too many consecutive elements filtered error with string(:printable)

### ISSUE THREAD

**Issue by axelson** [whatyouhide/stream_data#134]
I got the following error on a CI run:
> (StreamData.FilterTooNarrowError) too many consecutive elements were filtered out.
> To avoid this:
>     
>  * make sure the generation space contains enough values that the chance of a generated
> value being filtered out is small. For example, don't generate all integers and filter
> out odd ones in order to have a generator of even integers (since you'd be taking out
> half the generation space).

But my code just looks like:
```
  property "gen_initials/1 always returns a non-empty list" do
    check all name <- string(:printable),
              name != "" do
      list = InitialGenerator.gen_initials(name)
      refute Enum.empty?(list)
    end
  end
```

Which only filters out a single element so I'm thinking that perhaps this is a bug in the `string(:printable)` generator?

NOTE: This doesn't happen very often, this is the first time I've run into it.

**Comment by whatyouhide** [comment]
> NOTE: This doesn't happen very often, this is the first time I've run into it.

If it doesn't happen very often, it could happen that `""` is generated a few times. If you need non-empty strings, use `string(:printable, min_length: 1)` and it should do the trick. Thanks for reporting!

**Comment by axelson** [comment]
@whatyouhide Okay, that makes sense. But does that mean that you shouldn't use filtering at all? Because if you can get this error filtering a single value out, I'd imagine it would be even more likely if you are filtering out multiple values.

**Comment by whatyouhide** [comment]
> NOTE: This doesn't happen very often, this is the first time I've run into it.

@axelson I think this might answer your question? There's a teeny tiny chance that filtering will fail and you encountered that chance. You can bump the number of max consecutive failures that the filter is allowed to have if you want to reduce those chances, but probability means that there will always be a chance that too many filtered-out cases will be generated. In general, yeah, filter is only good for filtering very specific cases that are very unlikely to be generated, otherwise generating good data in the first place is the way to go.
