### ISSUE TITLE
`negative_integer()`, `number()` and `timeout()` generators?

### ISSUE THREAD

**Issue by Qqwy** [whatyouhide/stream_data#157]
There are two types which are relatively common in code, which currently are not exposed as first-class generators by StreamData:

- `number()`. Currently you'll have to write `StreamData.one_of([StreamData.integer(), StreamData.float()])` manually. Generator for the `number()` type.
- `negative_integer()`. Currently, the best thing you can do is generate a positive integer and negate it. Generator for the `neg_integer()` type.
- `timeout()`. Currently you'll have to write `StreamData.one_of([StreamData.non_neg_integer(), :infinity])` manually. Generator for the `timeout()` type which is very common in e.g. OTP callbacks.

**Comment by Qqwy** [comment]
If we want these, I'll gladly contribute a PR :slightly_smiling_face:

**Comment by whatyouhide** [comment]
@Qqwy I want to always try to balance how many generators we add versus composability.

* `number/0`: as you showed, this is trivial as `one_of([integer(), float()])`, so I'd prefer to keep it simple and not add it.
* `neg_integer/0`: trivial to implement as `map(integer(), &(-abs(&1))`, so also not worth it IMO.
* `timeout/0`: this might be worth it because the `one_of(non_neg_integer(), :infinity)` implementation is not ideal as you'd generate `:infinity` way too many times. A more "useful" implementation could be something like `frequency([{1, :infinity}, {10, non_neg_integer()}])`. However, I don't want to implement this because I don't think OTP callbacks (and other things that use timeouts) are the sort of things you'd write property tests for.

Thanks for the suggestions though, appreciate them! 💟
