### ISSUE TITLE
Should bytes shrink?

### ISSUE THREAD

**Issue by whatyouhide** [whatyouhide/stream_data#16]
Right now `StreamData.byte/0` values don't shrink. I did this because my intuition tells me that the byte `30` is not "smaller" than the byte `230` because they're both bytes, but maybe it makes sense to shrink the bytes. This would also affect `StreamData.binary/0`.

\cc @josevalim

**Comment by josevalim** [comment]
I think we should shrink it because I take a byte to represent all bytes
and not a single byte. If I was testing a protocol and let's say the first
byte has to be 131, I would rather use a constant for that.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by tmbb** [comment]
> my intuition tells me that the byte 30 is not "smaller" than the byte 230

Wouldn't you prefer `<<0, 0, 0>>` to `<<45, 64, 2>>`? The former suggests that probably any three bytes will trigger the bug, or at least that the null byte (and important special case) triggers the bug. This is particularly important because we have no guarantee that the null byte will be generated on its own..
