### ISSUE TITLE
Testing specific examples

### ISSUE THREAD

**Issue by tmbb** [whatyouhide/stream_data#19]
Sometimes StreamData might find some interesting examples, which might be hard to find and which we want to test everytime. [Hypothesis](https://github.com/HypothesisWorks/hypothesis-python) deals with that by using the `@example` decorator:

```python
# Ensure this string is tested
@example(s="$%6!>Z")
# Given any string, test the invariants in the function below
@given(s=text())
def test_something(s):
    ...
```

There should be a way to make sure specific examples are tested. I suggest something like this:

```elixir
check all int1 <- int(),
          int2 <- int(),
          int1 > 0 and int2 > 0,
          sum = int1 + int2,
  # Before/after trying the generators, try these:
  trying_examples: [
    {int1: 1, int2: 2},
    {int1: 3, int2: 7}
  ] do
  assert sum > int1
  assert sum > int2
end
# alternatively, it could be examples: [...], with_examples: [...], etc. 
```

**Comment by josevalim** [comment]
since the check all syntax handles multiple generators, I would rather have
those cases be defined as a separate test case with readable descriptions
of the corner cases they aim to solve than add more syntax to the property
test API.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by tmbb** [comment]
Ok, I think I agree. I was never that keen on having a way to specify specific examples in the test anyway. An example is just an ExUnit test case, after all, and adding more syntax to what is already a very complex macro is problematic.

In any case, I thought this should be raised as an issue. Feel free to close this if unless you want more people to give their opinion.

**Comment by whatyouhide** [comment]
The reason why we don't support specific cases is exactly because `check all` is just a fancy big-ass assert. If you want to test on random data *and* specific data, just add the specific-data tests below/above the `check all`. If you have complex assertion logic that you don't want to repeat, extract the assertion logic instead. I think for now this works better than making the `check all` syntax and semantics even more complex.

I'm gonna close this issue for now, but feel free to reopen if you have further things to discuss, same goes for everybody else interested in the discussion (just post here).

Thanks @tmbb! 💟
