### ISSUE TITLE
Add a term/0 generator

### ISSUE THREAD

**Issue by xadhoom** [whatyouhide/stream_data#32]
Sometimes is useful to test for any term(), so instead of defining a custom generator which maps all generators in StreamData, something like:

    def terms_generator do
      StreamData.one_of([
        StreamData.byte(), StreamData.integer(), StreamData.binary(),
        StreamData.bitstring(), StreamData.boolean(),
        StreamData.iolist(), StreamData.iodata(), StreamData.uniform_float(),
        StreamData.unquoted_atom()
      ])
    end

can be very useful to have built-in helper like StreamData.term() or StreamData.any() since is a generic one and maps to basic typespecs.

**Comment by josevalim** [comment]
Can you give an example of a term generator? I guess for example many of the functions in Enum don't care about their contents? Maybe it is better to call it `any` though?

**Comment by jeffkreeftmeijer** [comment]
For example; PropEr has [`:proper_types.term/0`](https://github.com/manopapad/proper/blob/master/src/proper_types.erl#L1189), which is an alias for [`:proper_types.any/0`](https://github.com/manopapad/proper/blob/master/src/proper_types.erl#L1114-L1120). It generates an integer, float, atom, bitstring, or a tuple or list of `any/0`. I agree that calling it `any/0` would be nicer (since that's what this is called in typespecs).

**Comment by josevalim** [comment]
Apologies, I wanted to say "an example of use of the term generator".

FWIW, typespecs have both `any` and `term`.

**Comment by xadhoom** [comment]
Something that maybe backed by Enum or :ets, where you can store anything and do something that's not directly related to the input data.

In my specific use case I have a cache that may store any (big) term and return a (small) ref to it (while doing other stuff).
So to test it I inject all possible terms and doing it in traditional tests means a test for each basic type and maybe also a combination of them.

`any` is maybe better.

Even if is not strictly `any` as in typespecs, because does not generates structured data like tuples or maps.

**Comment by xadhoom** [comment]
Is also true that (afaik) QuickCheck has not an any() generator, and is reasonable since is hard to define what any() really is and generate enough different terms to be close to a real any()...

**Comment by whatyouhide** [comment]
Not sure how to move on with this. I like the idea of having a generator that says "I don't care what this is because I'm testing a property of the container of this" or something similar, like the `Enum` example. Maybe we can start with `simple_term/0` (probably better name needed) that generates non-container terms and see where things go. Thoughts @josevalim?

**Comment by josevalim** [comment]
If the plan is to revisit it later, then `simple_term/0` is not a good name. It may be preferable to introduce `term/0` and have it at least generate empty lists / tuples / maps for now.

**Comment by whatyouhide** [comment]
Closed (for real this time) by #45.
