### ISSUE TITLE
Maybe have a way to customize shrinking

### ISSUE THREAD

**Issue by whatyouhide** [whatyouhide/stream_data#61]
Good example from propertesting.com:

```erlang
?SHRINK(range(0, 2000), [range(1970, 2000), ...])
```

**Comment by Mdlkxzmcp** [comment]
This could be passed as a option for the `use ExUnitProperties`  macro, which would have the benefit of using the desired "shink" to the entire test file if that is desired. 
Otherwise a custom shrinking could be passed as an optional check_all argument.

Both uses could be great on their own, but the combination would be even better ;3

**Comment by whatyouhide** [comment]
With the design of stream_data, this is a pain to implement, and I'm not sure it brings great value. 
I'll close the issue for now and if someone will need this in the future (for some real-life use cases) we can reopen it :)
