### ISSUE TITLE
StreamData representation leaks

### ISSUE THREAD

**Issue by josevalim** [whatyouhide/stream_data#80]
We say that the StreamData struct is private but we leak it during inspect:

    iex(4)> integer()
    %StreamData{generator: #Function<45.79517404/2 in StreamData.integer/0>}

My suggestion is to merge the function and StreamData representations:

    iex(4)> integer()
    #StreamData<45.79517404/2 in StreamData.integer/0>

**Comment by whatyouhide** [comment]
@josevalim do you want the exact representation you showed? Not sure how to achieve that, given that `Inspect.Function` has a lot of code for outputting the `45.79517404/2 in StreamData.integer/0` part. We also shouldn't extract it from the function representation IMO since `Inspect.Function` would get an algebra document. I guess we can extract it from `inspect(fun)`, how do you feel about that?

**Comment by josevalim** [comment]
Yeah, I was thinking this:

    case inspect(fun, opts) do
      "#Function<" <> rest -> "#StreamData<" <> rest
      other -> "#StreamData<#{other}>"
    end
