### ISSUE TITLE
Negative floats and numeric strings

### ISSUE THREAD

**Issue by Adzz** [whatyouhide/stream_data#87]
Hello, I have made a function like this:

```elixir
  def possibly_negative_float(max_float_size \\ 100) do
    StreamData.bind(StreamData.boolean(), fn negative? ->
      if negative? do
        StreamData.map(StreamData.uniform_float(), &(-(&1 * max_float_size)))
      else
        StreamData.map(StreamData.uniform_float(), &(&1 * max_float_size))
      end
    end)
  end
```
Is this something that you think may be worth including in stream data? I'd be happy to open a PR, but I'm not sure if you'd like it, or really how to test it.

The above function also allows this:

```elixir
  def numeric_string(max_float_size \\ 100) do
    StreamData.frequency([
      {5, NumericGenerators.integer |> StreamData.map(&Integer.to_string(&1))},
      {5, NumericGenerators.possibly_negative_float(max_float_size) |> StreamData.map(&Float.to_string(&1))},
    ])
  end
```

Which might be similarly helpful to the community.

Thanks!

**Comment by whatyouhide** [comment]
Hey @Adzz, it seems like you are using an old version of stream_data. I can't remember when it was introduced, but version 0.4 and on have `StreamData.float/1` instead of `uniform_float/0`, which also generates negative floats.

As for `numeric_string/1`, I don't think its place is in the core of stream_data. It seems like something specific to your application, there's nothing wrong in implementing it in your test suite. FWIW, the implementation is pretty compact if you write it like this:

```elixir
def numeric_string() do
  map(one_of([integer(), float[]), &to_string/1)
end
```

Let me know if this does it for you. If more people feel like `numeric_string/0` should be in core, we can reopen the discussion about that.

Thanks for the issue! 💟
